# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
   set_property IOSTANDARD LVCMOS33 [get_ports clk]
   create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]


set_property PACKAGE_PIN L3 [get_ports {adc[0]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {adc[0]}]
 set_property PACKAGE_PIN M3 [get_ports {adc[1]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {adc[1]}]

   set_property PACKAGE_PIN G19 [get_ports {vgaR[0]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaR[0]}]
   set_property PACKAGE_PIN H19 [get_ports {vgaR[1]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaR[1]}]
   set_property PACKAGE_PIN J19 [get_ports {vgaR[2]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaR[2]}]
   set_property PACKAGE_PIN N19 [get_ports {vgaR[3]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaR[3]}]
   set_property PACKAGE_PIN N18 [get_ports {vgaB[0]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaB[0]}]
   set_property PACKAGE_PIN L18 [get_ports {vgaB[1]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaB[1]}]
   set_property PACKAGE_PIN K18 [get_ports {vgaB[2]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaB[2]}]
   set_property PACKAGE_PIN J18 [get_ports {vgaB[3]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaB[3]}]
   set_property PACKAGE_PIN J17 [get_ports {vgaG[0]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaG[0]}]
   set_property PACKAGE_PIN H17 [get_ports {vgaG[1]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaG[1]}]
   set_property PACKAGE_PIN G17 [get_ports {vgaG[2]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaG[2]}]
   set_property PACKAGE_PIN D17 [get_ports {vgaG[3]}]
       set_property IOSTANDARD LVCMOS33 [get_ports {vgaG[3]}]
   set_property PACKAGE_PIN P19 [get_ports Hsync]
       set_property IOSTANDARD LVCMOS33 [get_ports Hsync]
   set_property PACKAGE_PIN R19 [get_ports Vsync]
       set_property IOSTANDARD LVCMOS33 [get_ports Vsync]
       
# Led's are used for debugging purposes.       
       set_property PACKAGE_PIN U16 [get_ports {led[0]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
       set_property PACKAGE_PIN E19 [get_ports {led[1]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
       set_property PACKAGE_PIN U19 [get_ports {led[2]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
       set_property PACKAGE_PIN V19 [get_ports {led[3]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
       set_property PACKAGE_PIN W18 [get_ports {led[4]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
       set_property PACKAGE_PIN U15 [get_ports {led[5]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
       set_property PACKAGE_PIN U14 [get_ports {led[6]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
       set_property PACKAGE_PIN V14 [get_ports {led[7]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
       set_property PACKAGE_PIN V13 [get_ports {led[8]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
       set_property PACKAGE_PIN V3 [get_ports {led[9]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
       set_property PACKAGE_PIN W3 [get_ports {led[10]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
       set_property PACKAGE_PIN U3 [get_ports {led[11]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
       set_property PACKAGE_PIN P3 [get_ports {led[12]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
       set_property PACKAGE_PIN N3 [get_ports {led[13]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
       set_property PACKAGE_PIN P1 [get_ports {led[14]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
       set_property PACKAGE_PIN L1 [get_ports {led[15]}]
           set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
